tools:
  - name: protein_pdb_request              # 0
    inputs:
      accession: 4EPT
  - name: structure_based_drug_design      # 1
    inputs:
      pocket: ./tmp/pocket_2025_03_04_03_43_57_412.pkl
  - name: protein_molecule_docking_score   # 2
  - name: export_molecule                  # 3
edges:
  - start: 0
    end: 2
  - start: 1
    end: 2
  - start: 1
    end: 3
  